### ISSUE TITLE
.distinct example?

### ISSUE THREAD

**Issue by martolini** [ReactiveKit/ReactiveKit#101]
```
let someCollection = CollectionProperty<[MyObject]>([])
let uniqueMatches = CollectionProperty<[Int]>([])
someCollection.map { $0.match }.distinct().bindTo(uniqueMatches)
```

What I want to achieve is to get all elements distinct on `match` of `someCollection` into `uniqueMatches`, how would I go about that?

`distinct` takes in two arguments of type `CollectionChangeSet`, which I find rather odd.

**Comment by srdanrasic** [comment]
Distinct operates on events in time, you're given previous stream element and new stream element.

The only way I see to solve your problem is by filtering duplicates

```swift
someCollection.map { $0.match }.filter { !uniqueMatches.contains($0) }.bindTo(uniqueMatches)
```

But that's not very nice and has O(n) complexity so I wouldn't recommend it on large arrays. 

I'll see if we can support binding of `CollectionProperty<Array<>>` to `CollectionProperty<Set<>>` in future.

**Comment by martolini** [comment]
I understand, so it's not to filter out distinct elements in the array - my bad.
