### ISSUE TITLE
Leaks #2

### ISSUE THREAD

**Issue by dimmdesign** [ReactiveKit/ReactiveKit#128]
Another member already posted this a while back. I've seen lots of RecursiveLock leaks due to ReactiveKit. Perhaps I'm not using the framework correctly. 

Is this correct? Any ideas?

![image](https://cl.ly/1U2K1a3s3p2H/Screen%20Shot%202016-12-17%20at%2019.57.16.png)

![image](https://cl.ly/2u2N02450k0p/Screen%20Shot%202016-12-17%20at%2020.04.56.png)

**Comment by srdanrasic** [comment]
I've seen that, but from my investigations it seems that Xcode/Instruments are reporting leaks incorrectly.

When all observations are disposed (in your example at the time of view controller deallocation - because you've put disposables in the controller's bag), all the NSRecursiveLocks that have initially been reported as leaks will actually get released and deallocated.

**Comment by dimmdesign** [comment]
:thumbsup:
