### ISSUE TITLE
throttle does not dispatch the last element

### ISSUE THREAD

**Issue by seanho** [ReactiveKit/ReactiveKit#149]
I am migrating from Bond 3 to 6 and notice the difference in the implementation of throttle. In Bond 3, throttle caches the last element and dispatch it on the specified queue when time is up, while in Bond 6, throttle drops the last element if it arrives within the throttle interval.

An example: throttle(seconds: 3)
arrives at 1 second: A
arrives at 2 second: B
arrives at 3 second: C
arrives at 4 second: D
arrives at 5 second: E

Expected: output signal includes C and E
Actual: output signal includes A and D

I am wondering if throttle is re-purposed for something different or if this is a bug. Unlike debounce, throttle doesn't take a DispatchQueue and does not have any async logic to handle throttle time up. Looking at the implementation below, it is not handling the else scenario, so basically the element arrives later is dropped instead of being handled later.
```swift
if lastEventTime == nil || now.rawValue > (lastEventTime! + seconds).rawValue {
    lastEventTime = now
    observer.next(element)
}
```

**Comment by seanho** [comment]
Having a deeper look into the debounce and throttle implementation, it's almost as if the behavior is swapped. I am working on a pull request to fix this, can you please verify if the current implementation is intentional or a mistake. Thanks!

**Comment by srdanrasic** [comment]
Hi @seanho, sorry for the slow response. I think the current implementation should be correct. `debounce` represents a window of certain amount of time that has to pass in order to propagate latest element. `throttle` propagates the first element and then filter events until certain amount of time passes after which it propagates another event if such happens.

http://rxmarbles.com/#debounce
