### ISSUE TITLE
Unexpected behaviour when sending failed event to observer

### ISSUE THREAD

**Issue by Cedrick84** [ReactiveKit/ReactiveKit#151]
Consider the following example code

```
public let searchText = Observable<String?>(nil)

searchText.ignoreNil().flatMapLatest { text -> Signal<String, NSError> in
                return Signal<String, NSError> { observer in
                    print(text)
                    if text == "123" {
                      observer.failed(NSError(domain: "dccdcd", code: -1, userInfo: nil))
                    } else {
                        observer.completed(with: text)
                    }
                    return BlockDisposable {
                        print("----------------- Disposing ------------------")
                    }
                }
                }.observe { (event) in
                    print(event)
                }.dispose(in: bag)
```

From the docs I understand that the behaviour of completed and failed should both indicate that the stream has ended. But in my code it clearly shows that it's not.

> We always finalize the sequence by sending either `.completed` or `.failed` event so that the receiver knows when the signal is over with event production.

When I start typing 1234 I get the following output in the console

```
Optional("")
----------------- Disposing ------------------
Optional("1")
----------------- Disposing ------------------
Optional("12")
----------------- Disposing ------------------
Optional("123")
failed(Error Domain=dccdcd Code=-1 "(null)")
```
This means I never get into the `return signal` code after the failed event is sent. Which means that in real life if a network request fails for whatever reason I cannot retry using the same binding. Any help would be greatly appreciated.

Thanks

**Comment by srdanrasic** [comment]
Hey @Cedrick84, that is expected behaviour of flatMapLatest/Concat/Merge. The "flatMapped" signal will not complete until both the inner signal(s) (what you return in flatMap) and the outer signal (searchText) complete. In your case the outer signal never completes (Observable completes when it gets deallocated) so your observer never receives `.completed` event. 

On the other hand, the failure event on the inner signal will propagate to the "flatMapped" signal and terminate it. That's how it works and it's the convenient behaviour for most cases.

In your case you could filter out terminal events from the inner signal so that the failure never get propagated. It will also not propagate completed, but that's not really important in this case.

```swift
searchText.ignoreNil().flatMapLatest { text -> Signal<String, NSError> in
        return Signal<String, NSError> { observer in
            ...
        }.ignoreTerminal()
    }.observe { (event) in
        print(event)
    }.dispose(in: bag)
```

You could also _materialize_ inner signal. That basically wraps signal events into `.next` elements so when you do `observeNext` you will receive an instance of `Event`.

```swift
searchText.ignoreNil().flatMapLatest { text -> Signal<String, NSError> in
        return Signal<String, NSError> { observer in
            ...
        }.materialize()
    }.observeNext { (event) in
        print(event)
    }.dispose(in: bag)
```

Hope this helps :)

**Comment by Cedrick84** [comment]
@srdanrasic thanks so much for the fast and good explanation.
