### ISSUE TITLE
Biggest difference/advantage over ReactiveSwift

### ISSUE THREAD

**Issue by vojtechvrbka** [ReactiveKit/ReactiveKit#170]
Hey All,

This is not really an issue but more a question.

I used ReactiveKit for past two years in my previous project.
I am now starting a new greenfield project and I am evaluating all frameworks that I used previously. 

I can't find any good comparison between ReactiveKit and ReactiveSwift. ReactiveSwift seems to have a bigger community and seems to be quite similar to ReactiveKit.

Can somebody point me to some comparison article or tell me in your own words why is ReactiveKit better? Thank you All.

**Comment by srdanrasic** [comment]
Thanks for asking this question!

I would not say that ReactiveKit is a better framework. There are pros and cons.

The goal for ReactiveKit is to be very simple and lightweight reactive framework. It's a balance between simplicity and comprehensiveness. ReactiveKit also aims to be easy to use and derives that from its simplicity.

Main conceptual difference is that ReactiveSwift makes a distinction between so called hot and cold observables with Signals and SignalProducers. ReactiveKit makes no such distinction and its signals are "cold" by default, but they can gain all benefits of "hot" signals by applying `shareReplay` operator to them. I still haven't heard of a good argument for rising that distinction to the type level. With respect to this, ReactiveKit is more aligned with RxSwift.

If one would compare ReactiveKit to RxSwift, the main conceptual difference would be in strongly typed errors. Here ReactiveKit takes approach similar to ReactiveSwift. That has few implications. 

In order to get compile-time guarantee that a signal/observable will not fail, Rx developer has to reach for Driver type from RxCocoa framework. Driver however also dispatches everything on the main thread and forces sequence sharing. In other words, it's an "all or nothing" solution. 

With ReactiveKit one can just specialize error to `NoError` or use `SafeSignal` typealias to get compile-time guarantee that Signal will not fail. 

In ReactiveKit, binding targets (like UIKit objects) define their execution contexts (threads) so the "main scheduler guarantee" of a Driver is not needed. Sequence sharing is done by applying `shareReplay` operator.

ReactiveKit provides basic reactive concepts that offer greatest possible flexibility. It tries to avoid "all or nothing" solutions.

I have used both ReactiveSwift and RxSwift and I can tell you that they are both great frameworks and you won't make a mistake by choosing any of them. Over the time I've evolved ReactiveKit to provide, what I think is, the best of all sides in a very simple form.

This comes at the cost of a smaller community (but with detailed Readme 😂) and not as comprehensive coverage of all possible reactive aspects and integrations, but with the benefit of using something very simple (just above 2k lines of code) so you can go into the code and see how it works. 90% of the framework is in the `SignalProtocol.swift` file.

ReactiveKit provides UIKit/AppKit integrations through Bond framework like ReactiveSwift provides it through ReactiveCocoa or RxSwift through RxCocoa.

Using Bond is optional and I personally find ReactiveKit enough for most of the projects I'm working on now that it has inlines bindings.

Hope this helps.

**Comment by vojtechvrbka** [comment]
Hey Srđan,

Thank you for the long explanation, I really appreciate it!

It's good for me to know the main differences because I had developers asking me quite a few times about the differences between ReactiveKit and other reactive frameworks.

I am going to stay with ReactiveKit as I prefer simplicity over complexity.

All the best and thanks!
