### ISSUE TITLE
AppKit extensions

### ISSUE THREAD

**Issue by srdanrasic** [ReactiveKit/ReactiveKit#4]
Should be separate framework. Here is the project: https://github.com/ReactiveKit/ReactiveAppKit.

I'm currently working on porting what we have in Bond.

**Comment by tonyarnold** [comment]
I've ported across a lot of what's in Bond, here: https://github.com/tonyarnold/ReactiveAppKit

Feel free to grab what you want :+1:

**Comment by srdanrasic** [comment]
Thanks @tonyarnold. I've been away for past couple of months, but I'm coming back soon and will port that as well as make some tweaks and improvements to the frameworks.

**Comment by tom-ashe** [comment]
Nice work, @srdanrasic and @tonyarnold! 

I've given this code a go over the weekend and the NSTableView is working well, so far.

I've run into unexpected results with binding a String and an NSTextField, however. 

Observations: 

1) I'm able to bind an NSTextField to a String, but not the inverse.
2) On invoking observe to the String and the NSTextField, the NSTextField only calls the closure  on observe, not on subsequent value changes.
3) The bind of NSTextField to a string does not update the String on change of the NSTextField
4) The property on the NSControl extension is called "rStringleValue". Is this intentional or a typo for "rStringValue"?

Any thoughts?

Below is the code I'm using in the VoewController after creating a default swift project in xcode.


`import Cocoa
import ReactiveKit
import ReactiveAppKit

class ViewController: NSViewController {

    @IBOutlet var testField: NSTextField?
    var testString = Observable<String?>("")
    let disposeBag = DisposeBag()

    override func viewDidLoad() {
        super.viewDidLoad()

        // Do any additional setup after loading the view.
        testField?.stringValue = "foo"

        testField?.rStringleValue.bindTo(testString)

// Fails. Cannot invoke 'bindTo' with an argument list of type '(NSTextField?)'
//        testString.bindTo(testField)
        
        testField?.rStringleValue.observe { value in
            print(value)
        }.disposeIn(self.disposeBag)
        
        testString.observe { value in
            print(value)
        }.disposeIn(self.disposeBag)
        
        testField?.stringValue = "bar"
        
        testString.value = "baz"
    }

    deinit {
        self.disposeBag.dispose()
    }

    
    override var representedObject: AnyObject? {
        didSet {
        // Update the view, if already loaded.
        }
    }
}`

**Comment by catalandres** [comment]
@srdanrasic Instead of duplicating all the amazing job you have already done in Bond, why don't you just add it as a subproject? Easier to maintain, no?

**Comment by srdanrasic** [comment]
This is now part of Bond framework.
