### ISSUE TITLE
Applying filter / sort / etc.. on a CollectionProperty returns a Stream of CollectionChangeset

### ISSUE THREAD

**Issue by rsaarloos** [ReactiveKit/ReactiveKit#59]
Hi,

In version 2.0 if you apply for example a sort operation on a `CollectionProperty<T>` then the result is a `Stream<CollectionChangeset<[T]>>`

In version 1.x if we would apply a sort operation on a `ObservableCollection<T>` we would again get a `ObservableCollection<T>`.

Can you give me some background information about this change (if this was intended).

**Comment by rsaarloos** [comment]
To give a bit more information. Currently I resolve this with the code example below, but not sure if this is the correct way.

```swift
let unsortedCollection = CollectionProperty<[String]>([])
let sortedCollection = CollectionProperty<[String]>([])

unsortedCollection.sort{$0 < $1}.observeNext{ changeset in
       sortedCollection.update(changeset)
}
```

**Comment by srdanrasic** [comment]
It was bad design in v1. Because CollectionProperty is not a value type, you could have easily gotten into an unexpected state. Mapped ObservableCollection had a link to the parent ObservableCollection, but could have also been modified manually.

Now mapping / filtering / sorting operates only on event stream, just like in case of plain Property, so unexpected state cannot happen.

This is a bit restrictive, but old behaviour can be simulated just as you found ot. In beta4 I made CollectionProperty bindable so it's a bit simpler to do that what you're doing:

```swift
let unsortedCollection = CollectionProperty<[String]>([])
let sortedCollection = CollectionProperty<[String]>([])

unsortedCollection.sort{$0 < $1}.bindTo(sortedCollection)
```

**Comment by rsaarloos** [comment]
Great makes sense, appreciate the update in beta4. Will close the issues.
