### ISSUE TITLE
[Proposal] Change most of structs to class.

### ISSUE THREAD

**Issue by jechol** [ReactiveKit/ReactiveKit#66]
There seems no criterion what to choose between `class` and `struct`.
For example, `PushOperation` is `class`, while `Operation` is `struct`.

```
Operation: struct
PushOperation: class
Stream: struct
PushStream: class

RawStream: struct
RawConnectableStream: class

Property: class
CollectionProperty: class

Observer: struct

most of Disposable: class
NotDisposable: struct
```

I think all of above types are semantically reference type, not value type, so they should be `class`, not `struct`.

Strong evidence is that above types are not feasible to adopt `Equatable` protocol.
See [WWDC 2015: Building Better Apps with Value Types in Swft](https://youtu.be/av4i3x-aZbM?t=18m30s) that says

> **"Value types should implement Equatable"**

If you agree, I can do the work.

**Comment by Danappelxx** [comment]
Personally, I think a good convention is "struct by default", since `struct`s provide various performance improvements/optimizations and there's often no reason to make them reference types. 

I haven't look at the codebase in detail, but for example I don't see any reason for [`Observer`](https://github.com/ReactiveKit/ReactiveKit/blob/master/Sources/Observer.swift#L37) to be a `class`, since it's just a container. It looks like reference types are only used when there are properties that are mutable, but it doesn't make sense for any references to the class itself to be marked mutable with `var` (such as with [`Property`](https://github.com/ReactiveKit/ReactiveKit/blob/master/Sources/Property.swift#L31)).

**Comment by jechol** [comment]
I agree "struct by default" if we are talking about type that has value semantics.
Here, above types have nothing to do with value semantics.

Does it make sense to compare `Observer` with another `Observer` with `==`?
We can't even compare two `Observer`that have same `observer: Event -> Void` because function types do not have `==`.

`struct` is value type. Value type should have value semantics. It's simple.

(Performance is not related here, and usually over emphasized)

**Comment by Danappelxx** [comment]
>Does it make sense to compare Observer with another Observer with ==?
It doesn't. But, I disagree with the statement that _every_ `struct` has to implement `==`.

>(Performance is not related here, and usually over emphasized)
I agree, that's a weak point.

Anyway, it's up to @srdanrasic. But, if it were up to me, I would continue the '`struct` by default' convention and not change what there is right now (don't fix what isn't broken, you know?).

**Comment by jechol** [comment]
Refactoring is fixing what is not broken.

Framework code like ReactiveKit should be fixed before others depend on, even it's not broken.
This is different situation with "Don't fix what isn't broken" can be applied (usually application code).

**Comment by srdanrasic** [comment]
Struct and value types in general are preferred choice. There are so many benefits that listing them here would take hours. Google "swift struct vs class". 

Criteria is identity. If something has identity, it will be a class. Types like PushStream/PushOperation, connectables and properties have identity so they are classed. They have identity because they hold an array of observers which are closures. Closures are reference types. When something holds references or an array of references it can no longer be treated as a pure value type.

**Comment by jechol** [comment]
Sorry for my stubborn opinion. But here I am again. :-) 

You said,
> When something holds references or an array of references it can no longer be treated as a pure value type.

`RawStream` holds `producer` which is reference type. As you said, it can no longer be treated as a pure value type.

If then, it should be class. Am I wrong?

**Comment by srdanrasic** [comment]
Ah, persistence is good! :) 

Yeah, there is more to this, and it's related usage.

For example, if we made Property a struct and pass it in a function, the receiver would expect that he's getting a copy of it and that the changes he makes are limited to his local scope / function body. However, the Property internally holds an array of observers, and because observers are closures and thus reference types, the copy of Property received by the function would hold references to those same observers. Any changes made in the scope of a function would affect those external observer.

We thus have Property as a reference type so that the receiver cannot make such assumptions.

With Stream/Operation `producer` we don't care if we are getting a copy or a reference, because the producer is a function meant to be called at will, when we need to produce the stream. It's something that cannot (should not) put an app in an inconsistent state or trigger unexpected side effects.

Of course, just because the usage allows for Stream/Operation to be struct, it does not necessarily mean that it should be struct. There are other benefits like much better performance, thread safety, copy semantics, immutability etc.

Most of the Swift standard library is structs and value types and I think we should aim to that same philosophy.
