### ISSUE TITLE
Crash when changing a collection thats filtered and bound to tableview

### ISSUE THREAD

**Issue by kh0r** [ReactiveKit/ReactiveKit#86]
According to https://github.com/ReactiveKit/ReactiveKit/issues/59 I bind my filtered collection to a new collection, which is further bound to a tableview:

```
let entries: CollectionProperty <[String]> = CollectionProperty([....])
let filteredItems: CollectionProperty <[String]> = CollectionProperty([])

entries.filter{ randomString in
...
}.bindTo(filteredItems)

filteredItems.bindTo(tableView) {
....
}
```

Ehen I change the filter condition and call the `entries.filter(..).bindTo` part, it correctly filters my items. But after I add or remove an item from the `entries` collection. The application crashes with an NSInternalInconsistencyException:
```
2016-06-29 11:43:06.979 reactivetableview[5047:4369665] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'attempt to delete row 19 from section 0 which only contains 9 rows before the update'
```

**Comment by srdanrasic** [comment]
Thanks for reporting this, I'll investigate.

**Comment by srdanrasic** [comment]
Hey @kh0r, I can't seem to find a way to reproduce this. Could you provide any additional details? For example, exact operations that you're doing to the array.

**Comment by kh0r** [comment]
I uploaded a sample project for easy reproduction: https://github.com/kh0r/reactivekit-tableview

**Comment by srdanrasic** [comment]
Hi @kh0r, thanks for the sample project! 

I've investigated this and the issue seems to be in the sample project itself. You're establishing multiple bindings. Each time you call `filterCollection()` you create one additional binding. Because of that, same changes are being propagated multiple times.

When I save the disposable and dispose is before establishing of a new binding, it works correctly.

```swift
  var bindingDisposable: Disposable? = nil

  func filterCollection(){
    bindingDisposable?.dispose()
    bindingDisposable = entries.filter{ randomString in
      return self.showAll || randomString.hash%2 == 0
    }.bindTo(filteredItems)
  }
```

I should probably update the documentation to make a note of such use case.

Hope this helps!

**Comment by kh0r** [comment]
Ah, that makes sense. Thank you very much!

Awesome work btw!
