### ISSUE TITLE
Enhancement: ObservableCollection propagate events up to super collection

### ISSUE THREAD

**Issue by startupthekid** [ReactiveKit/ReactiveKit#9]
It'd be great if I could have an `ObservableCollection` of type `ObservableCollection<T>` like this:

```
let observable: ObservableCollection<[ObservableCollection<[Model]>]>
```

such that any changes to the inner observable collection will propagate up to the outside observer. This relates to [this issue][1] in ReactiveUIKit, so that you can have a 2D array of observables which will allow the consumer to have multiple sections.

[1]: https://github.com/ReactiveKit/ReactiveUIKit/issues/2

**Comment by srdanrasic** [comment]
This is not necessary and would probably in most cases introduce unwanted behaviour. Whoever wants to observe inner collections can just iterate over all of them and register an observer for each of them. He would also observe outer collection so that he can update its observings when new inner collection are updated or deleted.
